
#!/bin/bash
#SBATCH -J lammps_build
#SBATCH -o /scratch1/06280/mcawood/benchpro/apps/frontera/cascadelake/intel22/intel22impi/lammps/23Jun2022/default/stdout.log
#SBATCH -e /scratch1/06280/mcawood/benchpro/apps/frontera/cascadelake/intel22/intel22impi/lammps/23Jun2022/default/stderr.log
#SBATCH -p development
#SBATCH -t 01:00:00
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -A A-ccsc
echo "START `date +"%Y"-%m-%dT%T` `date +"%s"`"

echo "JobID:    ${SLURM_JOB_ID}"
echo "User:     ${USER}"
echo "Hostlist: ${SLURM_NODELIST}"

export   working_path=/scratch1/06280/mcawood/benchpro/apps/frontera/cascadelake/intel22/intel22impi/lammps/23Jun2022/default/build
export   install_path=/scratch1/06280/mcawood/benchpro/apps/frontera/cascadelake/intel22/intel22impi/lammps/23Jun2022/default/install
export     local_repo=/scratch1/06280/mcawood/benchpro/repo
export        version=23Jun2022
export      opt_flags='-O2 -xCORE-AVX512 -sox'
export            exe=lmp_intel_cpu_intelmpi
export    build_label=default
export        threads=8

# Create application directories
mkdir -p ${install_path}
mkdir -p ${working_path} && cd ${working_path}


# [config]
export                 arch=cascadelake
export            opt_flags='-O2 -xCORE-AVX512 -sox'
export          build_label=default
export              bin_dir=
export                  exe=lmp_intel_cpu_intelmpi
export        collect_stats=True
export     script_additions=
export           local_repo=/scratch1/06280/mcawood/benchpro/repo
export                cores=56
export                nodes=1
export               stdout=stdout.log
export               stderr=stderr.log

# [modules]
export            compiler=intel/22.1.2
export                 mpi=intel22/impi/22.1.2

# Load modules
ml use /scratch1/hpc_tools/benchpro-dev/modulefiles
ml use /scratch1/projects/compilers/modulefiles
ml benchpro
ml $compiler
ml $mpi
ml

# Stage Files
stage https://download.lammps.org/tars/lammps-stable.tar.gz

# Compiler variables
export      CC=icc
export     CXX=icpc
export      FC=ifort
export     F77=ifort
export     F90=ifort
export   MPICC=mpicc
export  MPICXX=mpicxx
export MPIFORT=mpifort
export  MPIF90=mpif90

#------USER SECTION------
cd lammps-${version}/src

make yes-user-intel
make yes-user-omp

make package-status

make intel_cpu_intelmpi -j${threads}

cp ${exe} ${install_path}

#------------------------
ldd ${install_path}/lmp_intel_cpu_intelmpi
echo "END `date +"%Y"-%m-%dT%T` `date +"%s"`"

